### ISSUE TITLE
The problem with HUD in the MvM mode

### ISSUE THREAD

**Issue by coldcheek** [AleksiVibes/RenHud-V2#8]
Faced with the problem that when you press F4, the time timer is not displayed in the game, only some kind of square appears from below, and also disappears if you remove F4. The second problem is the complete lack of progress of the wave during it. That is, before starting and pressing F4, the total number of robots on the wave is shown, during the game it simply disappears, and sometimes it happens that only some types of support are shown, like sentry buster, snipers or spies. The third problem is related to the fact that the progress bar is also broken. Yesterday, when playing the official MVM, there was a problem that the progress scale - throughout all 4 missions, regardless of the maps - it did not change, remaining pink. However, it was of the usual color on the local server and changed throughout the wave, this problem was not found, that is, the first two were preserved, and the third was somehow solved. 

![20221001064211_1](https://user-images.githubusercontent.com/114790467/193387331-fe500ace-ef70-41ac-81d4-c3b84b96b601.jpg)

![1](https://user-images.githubusercontent.com/114790467/193387416-7bcb85c4-3c42-4138-b1bd-0fda1f750570.jpg)

![20221001064223_1](https://user-images.githubusercontent.com/114790467/193387508-011938b0-415a-4ea9-bf95-10f5306dfcaa.jpg)

![20221001065234_1](https://user-images.githubusercontent.com/114790467/193387638-98199a8c-06c2-49d7-8be6-e9b53fc098d5.jpg)

**Comment by AleksiVibes** [comment]
The Wave Robot counter disappearing is an intentional game mechanic, not a hud issue. It can be toggle with `cl_mvm_wave_status_visible_during_wave 0/1`

**Comment by AleksiVibes** [comment]
The red square was the countdown label, which had non-existing font
Fixed in next release.
